import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TEMPLATES = [
    {
        id: 'email-professional',
        name: 'Professional Email',
        category: 'email',
        mode: 'business',
        icon: '📧',
        description: 'A highly structured, polished professional email for executive and business communication.',
        sections: ['Subject Line Options (Formal, Direct, Urgent)', 'Salutation', 'Opening Hook & Context', 'Core Message & Details', 'Benefits / Why It Matters', 'Clear Call to Action (CTA)', 'Professional Sign-off', 'Signature Block'],
        ai_prompt: 'You are an expert executive communications specialist. Write a highly polished, professional business email.\n\nGuidelines:\n1. Subject Line: Generate 3 high-performance subject line options.\n2. Opening: Connect immediately with the recipient, showing respect and brevity.\n3. Core: State the purpose within the first two sentences. Use bullet points for readability when listing details.\n4. CTA: End with one clear, actionable, and low-friction next step.\n5. Tone: Confident, respectful, clear, and professional. Avoid buzzwords.',
        variables: ['{{recipient_name}}', '{{sender_name}}', '{{company}}', '{{purpose}}', '{{key_details}}', '{{urgency_level}}'],
    },
    {
        id: 'email-cold-outreach',
        name: 'Cold Outreach Email',
        category: 'email',
        mode: 'marketing',
        icon: '🎯',
        description: 'Compelling cold outreach email designed to agitate pain points, offer value, and drive replies.',
        sections: ['Attention-Grabbing Subject Lines (Curiosity vs Benefit)', 'Personalized Opening Hook', 'Core Pain Point Identification', 'Value Proposition & Solution', 'Social Proof / Case Study Reference', 'Low-Commitment CTA', 'Signature & Professional Info'],
        ai_prompt: 'You are an elite B2B sales copywriter. Write a highly converting cold outreach email under 150 words.\n\nGuidelines:\n1. Hook: Start with a personalized line referencing a recent achievement or common context (do not start with "I hope this email finds you well").\n2. Pain Point: Agitate a specific pain point they are likely facing.\n3. Solution: Introduce how your solution solves it with a brief value proposition.\n4. Proof: State a specific metric achieved for a similar client.\n5. CTA: Use a soft, low-friction request (e.g. "Are you open to a brief chat next week?").',
        variables: ['{{prospect_name}}', '{{company}}', '{{pain_point}}', '{{solution}}', '{{social_proof_metric}}'],
    },
    {
        id: 'email-follow-up',
        name: 'Follow-up Email',
        category: 'email',
        mode: 'business',
        icon: '🔄',
        description: 'Polite but persistent follow-up email designed to add value, re-contextualize, and prompt action.',
        sections: ['Follow-up Subject Line', 'Polite Reference to Previous Message', 'Additional Value / Re-context', 'Urgency / Benefit Reinforcement', 'Simple Actionable Next Step', 'Closing'],
        ai_prompt: 'You are a professional business developer. Write a highly effective follow-up email.\n\nGuidelines:\n1. Context: Reference the previous message politely without sounding accusatory.\n2. Value: Add new value (a fresh insight, helpful link, or a simplified explanation).\n3. Clarity: Keep it extremely short (under 100 words).\n4. Call to Action: Provide a single, dead-simple question or next step.',
        variables: ['{{recipient}}', '{{previous_topic}}', '{{time_since}}', '{{new_value_insight}}'],
    },
    {
        id: 'blog-post',
        name: 'Blog Post',
        category: 'content',
        mode: 'creative',
        icon: '📝',
        description: 'Engaging, search-optimized blog post utilizing the Problem-Agitate-Solve (PAS) structure.',
        sections: ['Title Options (SEO & Click-worthy)', 'Hook / Introduction (Problem, Agitate, Solve)', 'Key Concept 1 (H2)', 'Key Concept 2 (H2)', 'Deep Dive / Implementation (H3)', 'Actionable Takeaways (H2)', 'Conclusion (H2)', 'Call to Action / Engagement Question'],
        ai_prompt: 'You are a world-class content marketer and SEO copywriter. Write a highly engaging, structured blog post.\n\nGuidelines:\n1. Structure: Use standard H1, H2, H3 hierarchy.\n2. Content: Lead with a hook (using the PAS formula: Problem, Agitate, Solve).\n3. Value: Provide concrete, actionable strategies, not generic advice.\n4. Readability: Use short paragraphs (2-3 sentences max) and bullet points.\n5. SEO: Integrate the target keyword naturally in headers and body.',
        variables: ['{{topic}}', '{{target_keyword}}', '{{audience}}', '{{word_count}}', '{{tone_style}}'],
    },
    {
        id: 'linkedin-article',
        name: 'LinkedIn Article',
        category: 'content',
        mode: 'business',
        icon: '💼',
        description: 'Thought leadership article designed for LinkedIn formatting, readability, and viral engagement.',
        sections: ['Catchy Title', 'Storytelling Hook', 'The Status Quo Challenge', 'The Paradigm Shift', 'Core Principles / Blueprint (Bullets)', 'Key Actionable Takeaways', 'Conclusion & Call to Engagement'],
        ai_prompt: 'You are a high-profile industry thought leader. Write an engaging LinkedIn thought leadership article.\n\nGuidelines:\n1. Hook: Start with a personal story, contrarian view, or striking industry insight.\n2. Tone: Authentic, professional, visionary, yet conversational.\n3. Formatting: Use single-sentence lines for impact, bold key takeaways, and bullet points.\n4. Engagement: Conclude with a question that prompts readers to comment.',
        variables: ['{{topic}}', '{{author_expertise}}', '{{industry}}', '{{contrarian_opinion}}'],
    },
    {
        id: 'how-to-guide',
        name: 'How-To Guide',
        category: 'content',
        mode: 'education',
        icon: '📚',
        description: 'Step-by-step tutorial featuring prerequisites, execution steps, pro-tips, and troubleshooting.',
        sections: ['Introduction & Learning Objectives', 'Prerequisites & Tools', 'Step 1: Setup & Initialization', 'Step 2: Core Execution', 'Step 3: Optimization & Finalizing', 'Pro Tips for Success', 'Troubleshooting Common Issues', 'Next Steps / Future Learning'],
        ai_prompt: 'You are an expert technical writer. Write a comprehensive, step-by-step How-To Guide.\n\nGuidelines:\n1. Clarity: Use clear, unambiguous, active-voice instructions.\n2. Step-by-Step: Break down instructions into logical steps with numbered headings.\n3. Practicality: Include concrete prerequisites and common error troubleshooting.\n4. Scannability: Highlight key terms and use code blocks or tables where appropriate.',
        variables: ['{{skill}}', '{{difficulty_level}}', '{{time_required}}', '{{prerequisites}}'],
    },
    {
        id: 'meeting-notes',
        name: 'Meeting Notes',
        category: 'business',
        mode: 'business',
        icon: '📋',
        description: 'Organized meeting summary capturing agendas, attendees, decisions, and action item registers.',
        sections: ['Meeting Details (Title, Date, Host)', 'Attendees & Apologies', 'Core Agenda Items', 'Detailed Discussion Summary', 'Decisions Approved', 'Action Item Register (Task, Owner, Deadline)', 'Next Meeting Schedule'],
        ai_prompt: 'You are a corporate governance and business efficiency specialist. Write organized, clear meeting notes.\n\nGuidelines:\n1. Action-Oriented: Clearly separate discussion points from decisions and action items.\n2. Accountability: Format the action items in a clean table or bulleted list mapping Task to Owner and Deadline.\n3. Brevity: Use concise language, omitting unnecessary discussions to focus on decisions and outcomes.',
        variables: ['{{meeting_type}}', '{{date}}', '{{attendees}}', '{{agenda_points}}'],
    },
    {
        id: 'executive-summary',
        name: 'Executive Summary',
        category: 'business',
        mode: 'business',
        icon: '📊',
        description: 'Concise summary utilizing the BLUF (Bottom Line Up Front) principle for strategic decisions.',
        sections: ['The Bottom Line (BLUF)', 'Context & The Challenge', 'Our Proposed Solution', 'Strategic Value & ROI', 'Financials & Resource Requirements', 'Next Steps & Decisions Required'],
        ai_prompt: 'You are a management consultant. Write a persuasive executive summary using the BLUF (Bottom Line Up Front) principle.\n\nGuidelines:\n1. BLUF: Put the most important conclusion or recommendation in the first paragraph.\n2. Business Case: State the problem, solution, ROI, and resource requirements clearly.\n3. Clarity: Avoid jargon; use simple, high-impact business terminology.\n4. Focus: Keep it strictly focused on facts and strategic decisions.',
        variables: ['{{project}}', '{{stakeholders}}', '{{decision_type}}', '{{estimated_cost}}', '{{key_benefit}}'],
    },
    {
        id: 'project-proposal',
        name: 'Project Proposal',
        category: 'business',
        mode: 'business',
        icon: '📑',
        description: 'Persuasive proposal detailing need assessments, timeline scopes, budgeting, and risk plans.',
        sections: ['Executive Summary', 'Problem Statement & Needs Assessment', 'Proposed Solution & Scope', 'Deliverables & Milestones', 'Project Timeline', 'Budget & Resource Allocation', 'Team & Expertise', 'Risk Assessment & Mitigation', 'Success Metrics & KPI Tracking'],
        ai_prompt: 'You are a professional business consultant. Write a persuasive, thorough Project Proposal.\n\nGuidelines:\n1. Problem-Oriented: Establish a clear, urgent problem statement.\n2. Solutions-Focused: Detail the scope, deliverables, and exact timelines.\n3. Pricing: Break down the budget and justify the investment.\n4. Assurance: Include risk assessment and mitigation strategies to build trust.',
        variables: ['{{project_name}}', '{{client}}', '{{budget_range}}', '{{duration}}', '{{primary_objective}}'],
    },
    {
        id: 'case-study',
        name: 'Case Study',
        category: 'business',
        mode: 'marketing',
        icon: '📊',
        description: 'Marketing case study showing customer success through Challenge-Solution-Results framework.',
        sections: ['Executive Summary', 'The Client & Industry Profile', 'The Challenge / Core Pain Points', 'The Solution / Implementation', 'The Results & Hard Metrics', 'Client Testimonial', 'Key Takeaways & Lessons'],
        ai_prompt: 'You are a B2B marketing specialist. Write a highly persuasive case study following the Challenge-Solution-Results (CSR) framework.\n\nGuidelines:\n1. Challenge: Establish the status quo and the high stakes.\n2. Solution: Explain why your solution was selected and how it was implemented.\n3. Results: Lead with hard data (e.g. % growth, hours saved, dollars saved).\n4. Storytelling: Frame the client as the hero, and your company as the guide.',
        variables: ['{{client_name}}', '{{industry}}', '{{key_metric}}', '{{timeframe}}', '{{challenge_details}}'],
    },
    {
        id: 'product-description',
        name: 'Product Description',
        category: 'marketing',
        mode: 'ecommerce',
        icon: '🛍️',
        description: 'E-commerce copy focusing on emotional benefit hooks, feature specs, and call-to-actions.',
        sections: ['Attention-Grabbing Headline', 'Core Value Proposition', 'Product Benefits (Bullet Points)', 'Technical Features & Specifications', 'Common Use Cases', 'Social Proof / Trust Signals', 'Call to Action'],
        ai_prompt: 'You are a conversion copywriting expert. Write a compelling product description.\n\nGuidelines:\n1. Angle: Focus on emotional benefits first, then technical features.\n2. Clarity: Describe exactly how the product solves the customer\'s problem.\n3. Formatting: Use bold text for key benefits, short paragraphs, and bullet points.\n4. CTA: Direct the customer to purchase with a strong call to action.',
        variables: ['{{product_name}}', '{{target_customer}}', '{{price_point}}', '{{key_feature}}', '{{key_benefit}}'],
    },
    {
        id: 'landing-page',
        name: 'Landing Page Copy',
        category: 'marketing',
        mode: 'marketing',
        icon: '🖥️',
        description: 'High-conversion SaaS landing page copy mapping benefits, social proof, and FAQs.',
        sections: ['Hero Section (Headline, Subheadline, CTA)', 'The Pain Point (AIDA Hook)', 'The Solution (Product Intro)', 'Features vs Benefits (Interactive Grid)', 'Social Proof & Testimonials', 'FAQ Section', 'Final CTA Section'],
        ai_prompt: 'You are a high-conversion SaaS landing page copywriter. Write the copy for a landing page.\n\nGuidelines:\n1. Hero: Craft a benefit-driven headline and supporting subheadline.\n2. Empathy: Write copy that connects with the visitor\'s frustration.\n3. Focus: Keep the language simple, persuasive, and centered around a single call to action.',
        variables: ['{{product}}', '{{target_audience}}', '{{primary_cta}}', '{{objections}}', '{{unique_selling_point}}'],
    },
    {
        id: 'ad-copy',
        name: 'Ad Copy (PPC/Social)',
        category: 'marketing',
        mode: 'marketing',
        icon: '📣',
        description: 'Multi-platform PPC and social ad hooks, headlines, and descriptions using AIDA.',
        sections: ['Ad Hook / Primary Text', 'Headline Options (Benefit-driven)', 'Description Options', 'Call to Action Options', 'Ad Angle Variations (Urgency, Social Proof, Direct Benefit)'],
        ai_prompt: 'You are a performance marketing specialist. Write high-performing ad copy variations.\n\nGuidelines:\n1. Format: Provide variations for social (Facebook/Instagram) and search (Google Ads).\n2. Curiosity: Write a hook that stops the scroll.\n3. Precision: Adhere to strict character limits (headlines under 30 chars, primary text under 125 chars).',
        variables: ['{{product}}', '{{platform}}', '{{audience}}', '{{offer}}', '{{marketing_hook}}'],
    },
    {
        id: 'press-release',
        name: 'Press Release',
        category: 'marketing',
        mode: 'journalism',
        icon: '📰',
        description: 'Official media release written in AP style, featuring structured lead hooks and quotes.',
        sections: ['FOR IMMEDIATE RELEASE Header', 'Headline (Engaging & Informative)', 'Subheadline', 'Dateline (City, State - Date)', 'Lead Paragraph (The 5 Ws)', 'Body Paragraphs (Context & Details)', 'Executive / Stakeholder Quotes', 'About Company / Boilerplate', 'Media Contact Info'],
        ai_prompt: 'You are a public relations specialist. Write a professional press release in AP Style.\n\nGuidelines:\n1. Lead: Include the Who, What, When, Where, and Why in the first paragraph.\n2. Quotes: Draft a professional, impact-driven quote from an executive.\n3. Tone: Maintain absolute objectivity; avoid marketing language or puffery.',
        variables: ['{{announcement}}', '{{company}}', '{{spokesperson}}', '{{date}}', '{{key_quote}}'],
    },
    {
        id: 'social-media',
        name: 'Social Media Post',
        category: 'social',
        mode: 'social_media',
        icon: '📱',
        description: 'Scroll-stopping post with emoji formatting, value delivery, and calls to action.',
        sections: ['The Hook Line', 'The Value / Story Body', 'Interactive Call to Action', 'Hashtag Cloud', 'Visual Image Suggestion / Prompt'],
        ai_prompt: 'You are an elite social media strategist. Write a highly engaging social media post.\n\nGuidelines:\n1. Hook: Write a scroll-stopping first sentence.\n2. Engagement: Invite comments, shares, or direct replies.\n3. Style: Format with clean line breaks, appropriate emojis, and clear tags.',
        variables: ['{{platform}}', '{{topic}}', '{{tone}}', '{{cta}}', '{{key_takeaway}}'],
    },
    {
        id: 'twitter-thread',
        name: 'Twitter/X Thread',
        category: 'social',
        mode: 'social_media',
        icon: '🧵',
        description: 'High-engagement viral thread format utilizing open loops, spacing, and numbers.',
        sections: ['Tweet 1: The Hook (Viral Angle)', 'Tweet 2: Context / The Problem', 'Tweet 3: Main Insight 1', 'Tweet 4: Main Insight 2', 'Tweet 5: Main Insight 3', 'Tweet 6: Conclusion & Actionable Tip', 'Tweet 7: CTA (Retweet / Newsletter Link)'],
        ai_prompt: 'You are a viral X/Twitter thread expert. Write a high-engagement thread.\n\nGuidelines:\n1. Hook: Frame Tweet 1 with an open loop or contrarian hook that forces a click.\n2. Readability: Use short lines, spacing, emojis, and numbering (1/, 2/).\n3. CTA: The final tweet must direct readers to retweet or click a link.',
        variables: ['{{topic}}', '{{expertise}}', '{{audience}}', '{{contrarian_hook}}'],
    },
    {
        id: 'linkedin-post',
        name: 'LinkedIn Post',
        category: 'social',
        mode: 'business',
        icon: '💼',
        description: 'Professional networking post detailing business realizations and career lessons.',
        sections: ['Hook Line (Scroll-Stopper)', 'The Story / Experience Context', 'The Key Pivot / Realization', 'Actionable Business Lesson', 'Call to Value / Discussion Prompt'],
        ai_prompt: 'You are a professional brand building expert. Write a LinkedIn post.\n\nGuidelines:\n1. Hook: Start with a personal quote, statistic, or challenging question.\n2. Format: Use single-sentence paragraphs to maximize mobile readability.\n3. Value: Emphasize business insights, career growth, or operational lessons.\n4. Comment Prompt: Ask an engaging, professional question at the end.',
        variables: ['{{topic}}', '{{personal_experience}}', '{{industry}}', '{{business_impact}}'],
    },
    {
        id: 'research-summary',
        name: 'Research Summary',
        category: 'academic',
        mode: 'academic',
        icon: '🔬',
        description: 'Formal scholarly summary detailing backgrounds, methods, findings, and discussions.',
        sections: ['Research Title', 'Abstract / Executive Summary', 'Background & Literature Review', 'Methodology & Research Design', 'Key Findings & Data Analysis', 'Discussion & Implications', 'Conclusions & Future Scope', 'Academic References'],
        ai_prompt: 'You are a senior academic researcher. Write a comprehensive Research Summary.\n\nGuidelines:\n1. Objectivity: Maintain an unbiased, formal, third-person perspective.\n2. Rigor: Explain the methodology clearly, detailing samples and controls.\n3. Precision: Cite findings using standard academic referencing templates (e.g. APA or Harvard).',
        variables: ['{{research_topic}}', '{{field}}', '{{methodology}}', '{{key_findings}}'],
    },
    {
        id: 'thesis-statement',
        name: 'Thesis Statement',
        category: 'academic',
        mode: 'academic',
        icon: '📜',
        description: 'Argue-based thesis statements containing stances, roadmaps, and conciseness.',
        sections: ['Topic & Scope Description', 'Main Argument / Position', 'Supporting Evidence Areas', 'Draft Thesis Statement Options (3 variations)'],
        ai_prompt: 'You are an academic writing coach. Craft 3 variations of a strong, arguable Thesis Statement.\n\nGuidelines:\n1. Clear Stance: Ensure each statement takes a definitive, arguable position.\n2. Roadmap: Include a brief summary of the supporting arguments.\n3. Clarity: Keep the statements concise, specific, and direct.',
        variables: ['{{topic}}', '{{discipline}}', '{{scope}}', '{{core_argument}}'],
    },
    {
        id: 'api-documentation',
        name: 'API Documentation',
        category: 'technical',
        mode: 'technical',
        icon: '🔧',
        description: 'Detailed developer documentation for API routes, query schemas, and success/error responses.',
        sections: ['Endpoint Route & HTTP Method', 'Description & Use Cases', 'Authentication & Headers', 'Path & Query Parameters', 'Request Body JSON Schema', 'Request Payload Example', 'Response Body JSON Schema (Success & Error)', 'Error Responses & Code Explanations'],
        ai_prompt: 'You are a senior developer relations engineer. Write comprehensive API documentation.\n\nGuidelines:\n1. Standard Formatting: Use clear code blocks for requests, responses, and schemas.\n2. Completeness: Detail all parameters, their types, required flags, and constraints.\n3. Clarity: Keep description concise and directly focused on endpoint capabilities.',
        variables: ['{{endpoint}}', '{{method}}', '{{auth_type}}', '{{parameters}}', '{{success_response}}'],
    },
    {
        id: 'readme',
        name: 'README.md',
        category: 'technical',
        mode: 'technical',
        icon: '📖',
        description: 'Comprehensive project README containing quick-starts, env setups, and references.',
        sections: ['Project Title & Badge Grid', 'Short Project Description', 'Key Features', 'System Prerequisites', 'Quick Start / Installation Steps', 'Configuration & Env Variables', 'Usage Examples', 'API Reference / Documentation Links', 'License & Authors'],
        ai_prompt: 'You are a principal open source maintainer. Write a professional README.md.\n\nGuidelines:\n1. Style: Use clean Markdown tables, lists, and code blocks.\n2. Developer-Friendly: Focus on making local setup as friction-free as possible.\n3. Completeness: Cover configuration, contributing guidelines, and basic licenses.',
        variables: ['{{project_name}}', '{{language}}', '{{license}}', '{{dependencies}}'],
    },
    {
        id: 'release-notes',
        name: 'Release Notes',
        category: 'technical',
        mode: 'technical',
        icon: '🚀',
        description: 'Versioned product notes highlighting fixes, improvements, and migration alerts.',
        sections: ['Version Release Header', 'Release Date & Author', 'Executive Summary / Highlights', 'New Features (Feature + Benefit)', 'Improvements & Refactoring', 'Bug Fixes & Patches', 'Breaking Changes & Deprecations', 'Migration Instructions'],
        ai_prompt: 'You are a product manager. Write clear, developer-facing Release Notes.\n\nGuidelines:\n1. Customer Value: Focus on how the updates benefit the developer or customer.\n2. Breaking Changes: Highlight any regressions or breaking changes clearly with red indicators or warning blocks.\n3. Action-Oriented: Provide precise step-by-step instructions for migration.',
        variables: ['{{version}}', '{{product}}', '{{date}}', '{{features_added}}'],
    },
    {
        id: 'terms-of-service',
        name: 'Terms of Service',
        category: 'legal',
        mode: 'legal',
        icon: '📜',
        description: 'Legal terms and conditions specifying services, liability limits, and dispute laws.',
        sections: ['ToS Agreement Header', 'Use of Service & Account Creation', 'User Behavior & Restrictions', 'Intellectual Property Rights', 'Liability & Indemnification Limit', 'Termination & Suspensions', 'Dispute Resolution & Governing Law', 'ToS Updates & Contact'],
        ai_prompt: 'You are a corporate legal counsel. Write a clear, binding Terms of Service agreement.\n\nGuidelines:\n1. Precision: Use clear, unambiguous legal definitions to protect corporate interests.\n2. Plain English: Balance legal rigor with plain language explanations for key user clauses.\n3. Compliance: Account for jurisdiction-specific regulations.',
        variables: ['{{company}}', '{{service}}', '{{jurisdiction}}', '{{user_age_limit}}'],
    },
    {
        id: 'privacy-policy',
        name: 'Privacy Policy',
        category: 'legal',
        mode: 'legal',
        icon: '🔒',
        description: 'GDPR/CCPA compliant policy stating processing rules, user rights, and retention scopes.',
        sections: ['Privacy Introduction & Scope', 'Information We Collect (Direct vs Automated)', 'How We Process & Use Information', 'Data Sharing & Third-Party Integrations', 'Cookies & Tracking Disclosures', 'Global Rights (GDPR, CCPA, HIPAA)', 'Data Retention & Security Protocol', 'Policy Updates & Contact Details'],
        ai_prompt: 'You are a global data compliance officer. Write a GDPR and CCPA compliant Privacy Policy.\n\nGuidelines:\n1. Transparency: Be extremely transparent about exactly what data is collected, how it is stored, and who it is shared with.\n2. User Rights: Outline user data download and deletion rights clearly.\n3. Compliance: Match legal terminology to GDPR and CCPA standard definitions.',
        variables: ['{{company}}', '{{website}}', '{{data_types}}', '{{cookie_opt_out}}'],
    },
    {
        id: 'job-description',
        name: 'Job Description',
        category: 'hr',
        mode: 'hr_recruitment',
        icon: '💼',
        description: 'Outcome-based job description outlining remote/onsite details, missions, and skillsets.',
        sections: ['Role Title & Location (Remote/Onsite)', 'About Company & Culture', 'The Role Mission & Impact', 'Key Responsibilities (Outcome-based)', 'Required Technical Skills', 'Helpful Qualifications / Niceties', 'Salary, Benefits & Perks', 'Equal Opportunity Employer Statement'],
        ai_prompt: 'You are an expert talent acquisition manager. Write an inclusive, outcome-focused Job Description.\n\nGuidelines:\n1. Diversity: Avoid gendered terms or corporate clichés that reduce candidate pools.\n2. Outcome-based: Detail what the candidate will accomplish in the first 30/90 days rather than just listing skills.\n3. Clarity: Keep benefits, salary ranges, and requirements transparent.',
        variables: ['{{job_title}}', '{{department}}', '{{location}}', '{{experience_level}}', '{{salary_range}}'],
    },
    {
        id: 'performance-review',
        name: 'Performance Review',
        category: 'hr',
        mode: 'hr_recruitment',
        icon: '📈',
        description: 'Structured performance feedback outlining strengths, growth paths, and SMART goals.',
        sections: ['Performance Review Meta (Employee, Manager, Period)', 'Role Accomplishments & Outcomes', 'Core Professional Strengths', 'Identified Development Opportunities', 'Suggested Performance Goals (SMART)', 'Team Support & Action Plan', 'Overall Manager Rating'],
        ai_prompt: 'You are an experienced people manager and career coach. Write a balanced, constructive Performance Review.\n\nGuidelines:\n1. Specificity: Provide concrete examples of performance outcomes, not subjective opinions.\n2. Constructiveness: Frame development opportunities as growth paths with actionable steps.\n3. Goal-Oriented: Formulate 2-3 SMART performance goals for the next review cycle.',
        variables: ['{{employee_name}}', '{{role}}', '{{review_period}}', '{{accomplishments}}'],
    },
    {
        id: 'property-listing',
        name: 'Property Listing',
        category: 'real_estate',
        mode: 'real_estate',
        icon: '🏠',
        description: 'Descriptive listing details detailing luxury amenities, transport links, and pricing details.',
        sections: ['Property Headline (USP-driven)', 'Detailed Property Overview', 'Key Features & Amenities', 'Room-by-Room Breakdown', 'Local Community & Neighbourhood Benefits', 'Public Transit & Commuting Info', 'Price, Taxes & Terms of Sale', 'Viewing Scheduling & Contact Details'],
        ai_prompt: 'You are a luxury real estate marketing director. Write a compelling property listing.\n\nGuidelines:\n1. Imagery: Use highly sensory, descriptive vocabulary to help the buyer envision the home.\n2. Value: Highlight premium upgrades and unique architectural features.\n3. Context: Detail schools, nearby shopping, parks, and transit options to frame the neighborhood lifestyle.',
        variables: ['{{property_type}}', '{{location}}', '{{bedrooms}}', '{{price}}', '{{key_features}}'],
    },
    {
        id: 'destination-guide',
        name: 'Destination Guide',
        category: 'travel',
        mode: 'travel',
        icon: '✈️',
        description: 'Inspiring travel guide explaining dining scenes, neighborhoods, and practical logistics.',
        sections: ['Destination Intro & Atmosphere', 'Top Things to Do (Sightseeing & Activities)', 'Where to Stay (Neighborhood Profile)', 'Local Dining & Food Scene', 'Logistics, Packing & Best Time to Visit', 'Budget Guide & Money-Saving Tips', 'Cultural Etiquette & Local Advice'],
        ai_prompt: 'You are a professional travel journalist. Write a comprehensive, inspiring Destination Guide.\n\nGuidelines:\n1. Atmosphere: Start with evocative storytelling that captures the character of the place.\n2. Practicality: Detail accurate logistics, neighborhoods to stay in, and local dining recommendations.\n3. Insider Advice: Include off-the-beaten-path suggestions and local cultural etiquettes.',
        variables: ['{{destination}}', '{{trip_type}}', '{{duration}}', '{{local_specialties}}'],
    }
];

async function main() {
  console.log('🌱 Seeding ultimate templates into database...');
  for (const t of TEMPLATES) {
    await prisma.templates.upsert({
      where: { id: t.id },
      update: {
        name: t.name,
        category: t.category,
        mode: t.mode,
        icon: t.icon,
        description: t.description,
        ai_prompt: t.ai_prompt,
        variables: t.variables,
        sections: t.sections,
        is_default: true,
      },
      create: {
        id: t.id,
        name: t.name,
        category: t.category,
        mode: t.mode,
        icon: t.icon,
        description: t.description,
        ai_prompt: t.ai_prompt,
        variables: t.variables,
        sections: t.sections,
        is_default: true,
      },
    });
  }
  console.log('✅ Ultimate templates seeded successfully.');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
